CREATE TABLE RENTER(ID INT PRIMARY KEY AUTO_INCREMENT,
   NAME VARCHAR(30) NOT NULL,
  SURNAME VARCHAR(30) NOT NULL,
  PATRONYMIC VARCHAR(30) NOT NULL,
ADDRESS  VARCHAR(255) NOT NULL,
BIRTHDAY VARCHAR(30) NOT NULL,
PERSON  VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS RENTER;

CREATE TABLE RENTER(ID INT PRIMARY KEY AUTO_INCREMENT,
   NAME VARCHAR(30) NOT NULL
);

